# Generated by Django 4.1.5 on 2023-02-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.TextField(default='link'),
            preserve_default=False,
        ),
    ]
