# Generated by Django 4.1.5 on 2023-04-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='exit', upload_to=''),
            preserve_default=False,
        ),
    ]
