# Generated by Django 4.1.5 on 2023-04-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ban_expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
