# Generated by Django 4.1.5 on 2023-03-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_userprofile_reputation_alter_userprofile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
