# Generated by Django 4.1.5 on 2023-04-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_profile_ban_expiration_time_profile_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
