# Generated by Django 4.1.5 on 2023-03-25 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(default='nope', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.post'),
            preserve_default=False,
        ),
    ]
