# Generated by Django 4.1.5 on 2023-03-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Текст комментария'),
        ),
    ]
